---
sources:
    - name: meter_source
      interval: 600
      meters:
          - "*"
      sinks:
          - meter_sink
    - name: cpu_source
      interval: 600
      meters:
          - "cpu"
      sinks:
          - cpu_sink
          - cpu_memory_sink
          - cpuutil_memory_sink
    - name: disk_source
      interval: 600
      meters:
          - "disk.read.bytes"
          - "disk.read.requests"
          - "disk.write.bytes"
          - "disk.write.requests"
      sinks:
          - disk_sink
          - disk_read_write_sink
    - name: network_source
      interval: 600
      meters:
          - "network.incoming.bytes"
          - "network.incoming.packets"
          - "network.outgoing.bytes"
          - "network.outgoing.packets"
      sinks:
          - network_sink
    - name: memory_source
      interval: 600
      meters:
          - "memory.allocated"
      sinks:
          - cpu_memory_sink
          - cpuutil_memory_sink
    - name: host_cpu_source
      interval: 600
      meters:
          - "host.cpu.time"
      sinks:
          - host_cpu_time_sink
          - host_cpu_util_memory_usage_sink
    - name: host_memory_source
      interval: 600
      meters:
          - "host.memory.usage"
      sinks:
          - host_cpu_util_memory_usage_sink          
sinks:
    - name: meter_sink
      transformers:
      publishers:
          - notifier://
    - name: cpu_sink
      transformers:
          - name: "rate_of_change"
            parameters:
                target:
                    name: "cpu_util"
                    unit: "%"
                    type: "gauge"
                    scale: "100.0 / (10**9 * (resource_metadata.cpu_number or 1))"
      publishers:
          - notifier://
    - name: disk_sink
      transformers:
          - name: "rate_of_change"
            parameters:
                source:
                    map_from:
                        name: "disk\\.(read|write)\\.(bytes|requests)"
                        unit: "(B|request)"
                target:
                    map_to:
                        name: "disk.\\1.\\2.rate"
                        unit: "\\1/s"
                    type: "gauge"
      publishers:
          - notifier://
    - name: network_sink
      transformers:
          - name: "rate_of_change"
            parameters:
                source:
                   map_from:
                       name: "network\\.(incoming|outgoing)\\.(bytes|packets)"
                       unit: "(B|packet)"
                target:
                    map_to:
                        name: "network.\\1.\\2.rate"
                        unit: "\\1/s"
                    type: "gauge"
      publishers:
          - notifier://
    - name: disk_read_write_sink
      transformers:
          - name: "arithmetic"
            parameters:
                target:
                    name: "disk.read.write.bytes"
                    unit: "B"
                    type: "cumulative"
                    expr: "2*$(disk.read.bytes) + 2*$(disk.write.bytes)"
      publishers:
          - rpc://
    - name: cpu_memory_sink
      transformers:
          - name: "arithmetic"
            parameters:
                target:
                    name: "cpu_memory"
                    unit: "%"
                    type: "cumulative"
                    expr: "1*$(cpu) + 1*$(memory.allocated)"
      publishers:
          - rpc://
    - name: cpuutil_memory_sink              
      transformers:
          - name: "rate_of_change"
            parameters:
                apply_to:
                    - "cpu"
                target:
                    name: "cpu_util"
                    unit: "%"
                    type: "gauge"
                    scale: "100.0 / (10**9 * (resource_metadata.cpu_number or 1))"  
          - name: "arithmetic"
            parameters:
                apply_to:
                    - "*"
                target:
                    name: "cpuutil_memory"
                    unit: "%"
                    type: "cumulative"
                    expr: "1*$(cpu_util) + 1*$(memory.allocated)"
      publishers:
          - rpc://
    - name: host_cpu_time_sink
      transformers:
          - name: "rate_of_change"
            parameters:
                target:
                    name: "host.cpu.util"
                    unit: "%"
                    type: "gauge"
                    scale: "100.0 / (10**9 * (resource_metadata.cpu_number or 1))"
      publishers:
          - rpc://
    - name: host_cpu_util_memory_usage_sink              
      transformers:
          - name: "rate_of_change"
            parameters:
                apply_to:
                    - "host.cpu.time"
                target:
                    name: "host.cpu.util"
                    unit: "%"
                    type: "gauge"
                    scale: "100.0 / (10**9 * (resource_metadata.cpu_number or 1))"  
          - name: "arithmetic"
            parameters:
                apply_to:
                    - "*"
                target:
                    name: "host.cpu.util.memory.usage"
                    unit: ""
                    type: "cumulative"
                    expr: "1*$(host.cpu.util)/100 + 1*$(host.memory.usage)/100"
      publishers:
          - rpc://
